version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gradle-root:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/PersiCommons"
    schedule:
      interval: "weekly"
    groups:
      gradle-persicommons:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/VinoDomain"
    schedule:
      interval: "weekly"
    groups:
      gradle-vinodomain:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/VinoImporter"
    schedule:
      interval: "weekly"
    groups:
      gradle-vinoimporter:
        patterns:
          - "*"


  - package-ecosystem: "gradle"
    directory: "/priceservice"
    schedule:
      interval: "weekly"
    groups:
      gradle-priceservice:
        patterns:
          - "*"


  - package-ecosystem: "npm"
    directory: "/price-service-ui"
    schedule:
      interval: "weekly"
    groups:
      npm-price-service-ui:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/priceData"
    schedule:
      interval: "weekly"
    groups:
      pip-pricedata:
        patterns:
          - "*"