version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/PersiCommons"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/VinoDomain"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/VinoImporter"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/VinoDao"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/priceservice"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/VinoGUI"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/price-service-ui"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/priceData"
    schedule:
      interval: "weekly"